Repository charmed-hpc/filesystem-charms, pull requests merged in 2024-12, with the labels that each got.

#4 docs: add README.md and CONTRIBUTE.md
  CONTRIBUTE.md
  README.md
  tests/unit/test_interfaces.py
Labels: Type: Documentation, Type: Enhancement

#5 feat: add CODEOWNERS file
  .github/CODEOWNERS
Labels: enhancement

#3 ci: add publish action
  .github/workflows/publish.yaml
  lib/charms/filesystem_client/v0/filesystem_info.py
  tests/integration/server/lib/charms/filesystem_client/v0/filesystem_info.py
Labels: Type: Enhancement
